version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - CAMERA_IP=${CAMERA_IP}
      - USER=${USERBOT}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}
      - TOKEN=${TOKEN}
    restart: unless-stopped
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot-network:
    driver: bridge
